[build]
command   = "npm run build"
publish   = ".next"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.20.3"

[functions]
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"
