[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
