[build]
base = "RCS_v5399_masterSave"
command = "npm run build && npm run export"
publish = "out"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"
